<a href="https://colab.research.google.com/github/linda-bsharat/telco-customer-churn-prediction/blob/main/notebooks/01_data_cleaning_and_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#////////////////////////////////////
# Importing LIB
#///////////////////////////////////


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#////////////////////////////////////
# importing data
#///////////////////////////////////



url = "https://raw.githubusercontent.com/linda-bsharat/telco-customer-churn-prediction/main/data/telco_customer_data_v2.csv"
df = pd.read_csv(url)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST00001,Male,0,No,Yes,3.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,68.61,205.83,Yes
1,CUST00002,Male,1,Yes,No,2.0,Yes,Yes,DSL,No,...,No internet service,Yes,NaN,No,One year,Yes,Bank transfer (automatic),23.15,46.3,No
2,CUST00003,Female,No,No,No,42.0,Yes,Yes,DSL,No,...,No,NaN,Yes,Yes,Month-to-month,No,Electronic check,42.63,1790.46,Yes
3,CUST00004,Female,0,No,Yes,40.0,Yes,Yes,Fiber optic,No,...,Yes,No,No,No internet service,Month-to-month,No,Electronic check,75.04,3001.6,No
4,CUST00005,Male,Yes,Yes,Yes,17.0,Yes,NaN,Fiber optic,Yes,...,Yes,No,No internet service,No,Two year,Yes,Electronic check,22.38,380.46,Yes

part 1: fix the missing values

In [4]:
df.isna().sum().sort_values(ascending=False).head(15)

PaymentMethod       3569
Dependents          3565
Partner             3530
OnlineSecurity      2922
DeviceProtection    2894
StreamingTV         2827
StreamingMovies     2785
OnlineBackup        2747
TechSupport         2733
MultipleLines       1868
TotalCharges        1062
gender               748
SeniorCitizen        659
tenure               567
MonthlyCharges       388
dtype: int64

In [5]:
# =========================
# Handle Missing Values
# =========================

# yes/no service columns
service_cols = [
    "Dependents",
    "Partner",
    "OnlineSecurity",
    "DeviceProtection",
    "StreamingTV",
    "StreamingMovies",
    "OnlineBackup",
    "TechSupport",
    "MultipleLines",
]

df[service_cols] = df[service_cols].fillna("No")

In [6]:
df.isna().sum().sort_values(ascending=False).head(15)

PaymentMethod       3569
TotalCharges        1062
gender               748
SeniorCitizen        659
tenure               567
MonthlyCharges       388
Dependents             0
customerID             0
Partner                0
OnlineSecurity         0
PhoneService           0
MultipleLines          0
InternetService        0
TechSupport            0
DeviceProtection       0
dtype: int64

In [7]:
# =========================
# Fix TotalCharges type
# =========================

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# =========================
# Handle numeric missing (tenure, MonthlyCharges)
# =========================

df["tenure"] = df["tenure"].fillna(df["tenure"].median())
df["MonthlyCharges"] = df["MonthlyCharges"].fillna(df["MonthlyCharges"].median())

# =========================
# Impute TotalCharges using tenure * MonthlyCharges
# =========================

mask = df["TotalCharges"].isna()

df.loc[mask, "TotalCharges"] = (
    df.loc[mask, "tenure"] * df.loc[mask, "MonthlyCharges"]
)

In [9]:
df.isna().sum().sort_values(ascending=False)

PaymentMethod       3569
gender               748
SeniorCitizen        659
Partner                0
customerID             0
Dependents             0
tenure                 0
MultipleLines          0
PhoneService           0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
InternetService        0
TechSupport            0
StreamingTV            0
Contract               0
StreamingMovies        0
PaperlessBilling       0
MonthlyCharges         0
TotalCharges           0
Churn                  0
dtype: int64

In [10]:
# =========================
# Handle demographic missing values
# =========================

df["gender"] = df["gender"].fillna(df["gender"].mode()[0])
df["SeniorCitizen"] = df["SeniorCitizen"].fillna(df["SeniorCitizen"].mode()[0])

In [11]:
df.isna().sum().sort_values(ascending=False).head(3)

PaymentMethod    3569
gender              0
SeniorCitizen       0
dtype: int64

In [12]:
df["PaymentMethod"].value_count()

PaymentMethod
Electronic check             27841
Bank transfer (automatic)    14102
Mailed check                 13963
Credit card (automatic)      10400
BANK TRANSFER                  125
Name: count, dtype: int64

In [15]:
df[df["PaymentMethod"].isna()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
88,CUST00089,Female,1,No,No,14.0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,NaN,37.44,524.16,Yes
90,CUST00091,Male,0,No,No,22.0,Yes,No,DSL,No,...,No,No,No internet service,No,Month-to-month,Yes,NaN,41.19,906.18,Yes
109,CUST00110,FEMALE,No,No,No,11.0,Yes,Yes,DSL,No,...,No internet service,No,No,No internet service,Two year,Yes,NaN,18.39,202.29,No
113,CUST00114,Female,0,Yes,Yes,21.0,No,No phone service,Fiber optic,No,...,No,No,No,No,Two year,No,NaN,25.91,544.11,No
159,CUST00160,Male,0,No,Yes,10.0,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,NaN,29.91,299.10,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69874,CUST69875,Male,0,No,Yes,18.0,Yes,Yes,Fiber optic,No,...,Yes,No,No,Yes,One year,Yes,NaN,41.19,741.42,No
69901,CUST69902,Female,0,No,Yes,30.0,Yes,No,DSL,No,...,No,No,No,No,Two year,No,NaN,46.09,1382.70,No
69933,CUST69934,Female,No,Yes,Yes,35.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,NaN,41.19,1441.65,No
69936,CUST69937,Male,0,No,No,7.0,Yes,No,DSL,No,...,Yes,No,No,No,One year,Yes,NaN,29.43,206.01,Yes
69937,CUST69938,Female,1,No,No,23.0,Yes,No,Fiber optic,No,...,Yes,No internet service,No,No,Month-to-month,No,NaN,25.20,579.60,Yes

In [16]:
# =========================
# Handle PaymentMethod missing values
# =========================

df["PaymentMethod"] = df["PaymentMethod"].fillna(df["PaymentMethod"].mode()[0])

In [17]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64